#!/bin/sh
# ccstats — self-hosted Claude Code usage stats (badge firmware + server)
# Copyright (C) 2026 Zapador <zapador@zapador.net>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of version 2 of the GNU General Public License as published by the
# Free Software Foundation. See the LICENSE file for the full text.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# SCOPE REFRESHER (root) — keeps the collectors' mount namespace in sync with
# the set of users on the box, so NEW USERS ARE PICKED UP AUTOMATICALLY.
#
# The collector units run as the unprivileged 'ccollector' user with
# ProtectHome=tmpfs: /home is invisible except for what this script
# bind-mounts back in — each user's ~/.claude plus ~/projectname.txt (the
# display-name / 'ignore' override, which lives OUTSIDE ~/.claude).
#
# Installed to /usr/local/sbin/ccstats-refresh-scope by deploy.sh, which also
# installs ccstats-scope-refresh.{service,path,timer}: the .path unit fires on
# /home changes (user added/removed), the .timer sweeps every 10 min (catches
# ~/.claude appearing on a user's FIRST Claude Code run), and deploy.sh runs
# it synchronously at install time. Only paths that EXIST are listed, so the
# drop-in content changes exactly when the visible set should change; the two
# daemons are restarted only then (oneshot services pick it up on next start).
#
# Root-owned by design (it writes systemd drop-ins). It reads nothing but the
# directory listing of /home and takes no input — keep it that way.
set -eu

HOME_ROOT="${1:-/home}"
DROPIN_NAME="ccstats-scope.conf"
UNITS="claude-live-monitor claude-bottleneck-monitor ccstats-extract ccstats-usage ccstats-competitor ccstats-backup"
DAEMONS="claude-live-monitor claude-bottleneck-monitor"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
{
    echo "# Generated by ccstats-refresh-scope — DO NOT EDIT (rewritten when users change)."
    echo "[Service]"
    for h in "$HOME_ROOT"/*/; do
        [ -d "$h" ] || continue
        u="${h%/}"
        [ -d "$u/.claude" ]          && echo "BindReadOnlyPaths=-$u/.claude"
        [ -f "$u/projectname.txt" ]  && echo "BindReadOnlyPaths=-$u/projectname.txt"
    done
} > "$TMP"

changed=0
for s in $UNITS; do
    # only manage drop-ins for units that are actually installed
    [ -f "/etc/systemd/system/$s.service" ] || continue
    d="/etc/systemd/system/$s.service.d"
    if ! cmp -s "$TMP" "$d/$DROPIN_NAME" 2>/dev/null; then
        mkdir -p "$d"
        install -m644 "$TMP" "$d/$DROPIN_NAME"
        changed=1
    fi
done

if [ "$changed" = 1 ]; then
    systemctl daemon-reload
    for s in $DAEMONS; do
        systemctl try-restart "$s.service" 2>/dev/null || true
    done
fi
