# ccstats — self-hosted Claude Code usage stats (badge firmware + server)
# Copyright (C) 2026 Zapador <zapador@zapador.net>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of version 2 of the GNU General Public License as published by the
# Free Software Foundation. See the LICENSE file for the full text.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# GENERATED by tools/build-avatar-frames.py — DO NOT EDIT BY HAND.
#
# The sprite registry: metadata + lazy access to the per-sprite frame
# modules (avatar_sprite_<name>.py). Frames replicate the web avatar's CSS
# float/hop transforms (squash anchored at bottom-centre, nearest-neighbour
# at device pixels). Each frame is (translate_y, scale_x_milli,
# scale_y_milli, fill, shade, hi, dark, mouth, eyes_white, eyes_pupil,
# happy) with rects in device px relative to the 112 px sprite box origin —
# draw layer rects 1:1 (scale is baked in), offset by translate_y; the
# per-mille scale factors glue accessories (sweat bead) to the head through
# the same transform. Optional metadata keys (stress_marker / sparkle_pen /
# happy_pen) carry the web's per-avatar CSS specials; absent = default.

SPRITE_BOX = 112

FLOAT_CYCLE_MILLISECONDS = 2000           # avFloat duration (idle/waiting)
FLOAT_CYCLE_WORKING_MILLISECONDS = 950    # working speeds the float up
HOP_CYCLE_MILLISECONDS = 1150             # avHop duration (done flourish)

FRAME_SCALE_X = 1
FRAME_SCALE_Y = 2
LAYER_FILL = 3
LAYER_SHADE = 4
LAYER_HI = 5
LAYER_DARK = 6
LAYER_MOUTH = 7
LAYER_EYES_WHITE = 8
LAYER_EYES_PUPIL = 9
LAYER_HAPPY = 10

SPRITE_ORDER = ("gloom", "dimple", "volt", "miso", "noodle", "blip", "pip", "jelly", "dapper", "ziggy", "sparkly")

SPRITE_INFO = {
    "gloom": {
        "label": "GLOOM",
        "sweat_anchor": (63, 16),
    },
    "dimple": {
        "label": "DIMPLE",
        "sweat_anchor": (76, 12),
    },
    "volt": {
        "label": "ZAP",
        "sweat_anchor": (90, 16),
    },
    "miso": {
        "label": "MISO",
        "sweat_anchor": (76, 16),
    },
    "noodle": {
        "label": "NOODLE",
        "sweat_anchor": (87, 34),
    },
    "blip": {
        "label": "BLIP",
        "sweat_anchor": (90, 16),
        "happy_pen": 'eye_white',
    },
    "pip": {
        "label": "PIP",
        "sweat_anchor": (80, 34),
    },
    "jelly": {
        "label": "JELLY",
        "sweat_anchor": (72, 34),
    },
    "dapper": {
        "label": "DAPPER",
        "sweat_anchor": (72, 16),
    },
    "ziggy": {
        "label": "ZIGGY",
        "sweat_anchor": (76, 16),
        "eyes_white_on_top": True,
    },
    "sparkly": {
        "label": "FLICK",
        "sweat_anchor": (52, 16),
        "stress_marker": 'ember',
        "sparkle_pen": 'avatar_light',
    },
}

_loaded_sprites = {}


def sprite(name):
    """Metadata + frames for one sprite; the frame module imports on first
    use and stays cached (only visited sprites occupy RAM)."""
    if name not in _loaded_sprites:
        frame_module = __import__("avatar_sprite_" + name)
        entry = dict(SPRITE_INFO[name])
        entry["float"] = frame_module.FLOAT_FRAMES
        entry["hop"] = frame_module.HOP_FRAMES
        _loaded_sprites[name] = entry
    return _loaded_sprites[name]
