# ccstats — self-hosted Claude Code usage stats (badge firmware + server)
# Copyright (C) 2026 Zapador <zapador@zapador.net>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of version 2 of the GNU General Public License as published by the
# Free Software Foundation. See the LICENSE file for the full text.
#
# This program is distributed WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# GENERATED by tools/build-fonts.py — do not edit by hand.
#
# font_key -> (native_px, units_per_design_pixel). The .af files are
# quantized so one design pixel is exactly units_per_design_pixel .af
# units; the renderer scales glyphs by size/128, so drawing at
#   size = 128 * requested_px / (units * native_px)
# makes every design pixel exactly requested_px/native_px screen pixels
# (integer strokes, bearings and advances — no sub-pixel phase).
FONT_METRICS = {
    'pico': (8, 15),
    'silk': (8, 14),
    'silk_bold': (8, 12),
    'visitor_tt1': (10, 15),
    'aurora_24': (9, 6),
    'deer_diary': (11, 11),
    '5x7_mt_pixel': (7, 18),
    '5x5_mt_pixel': (5, 18),
    '3x5_mt_pixel': (5, 18),
}
